- name: Install mongodb component
  hosts: localhost
  become: yes
  tasks:
  - name: copy mongo rep to yum.repos.d
    ansible.builtin.copy:
      src:  mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: installing mongodb
    ansible.builtin.yum:
      name: mongodb-org
      state: installed
  # start & enable mongodb using service module
  - name: start & enable mongodb
    ansible.builtin.service:
      name: mongodb
      state: started
      enabled: yes
  - name: enable remote connections
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  - name: restart mongodb
    ansible.builtin.service:
      name: mongodb
      state: restarted



